version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: prism-media
    versions:
    - 1.2.3
    - 1.2.5
    - 1.2.6
    - 1.2.7
    - 1.2.8
  - dependency-name: ytdl-core
    versions:
    - 4.4.5
